disabled_rules:
- trailing_whitespace
opt_in_rules:
- empty_count
- empty_string
line_length: 510
ignores_function_declarations: true
ignores_comments: true
ignores_urls: true
excluded:
- Pods
- AppDelegate.swift
- FilmClubCannes/Model/ApiMovieDetail.swift
- FilmClubCannes/Model/Movies.swift
- FilmClubCannes/Model/ApiServices.swift
- FilmClubCannesTests/AlamofireTests/ApiTestsCase.swift
