disabled_rules:
- trailing_whitespace
- type_name
- variable_name
- variable_name_min_length
identifier_name:
excluded:
- id
opt_in_rules:
- empty_count
- empty_string
line_length: 510
ignores_function_declarations: true
ignores_comments: true
ignores_urls: true
excluded:
- Pods
- AppDelegate.swift
